version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
    volumes:
      - ./image_tags_app/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db-data:/var/lib/mysql
    restart: always

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql+pymysql://mbit:mbit@db:3306/Pictures
    volumes:
      - images-data:/app/images
    restart: always

volumes:
  db-data:
  images-data:
